apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "link-shortener-config-server-dev-role"
        vault.hashicorp.com/agent-inject-secret-github.token: "kv/data/dev/link-shortener-config-server/config"
        vault.hashicorp.com/agent-inject-template-github.token: |
          {{- with secret "kv/data/dev/link-shortener-config-server/config" -}}
          {{- .Data.data.githubToken -}}
          {{- end -}}

    spec:
      serviceAccountName: config-server
      containers:
        - name: helm
          image: your-image:tag
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret-github.token
                  key: secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}