spring:
  profiles:
    active: "dev"

vault:
  role: "link-shortener-config-server-dev-role"
  secretPath: "kv/data/dev/link-shortener-config-server/config"
  secretTemplate: |
    {{- with secret "kv/data/dev/link-shortener-config-server/config" -}}
    {{- .Data.data.privateKey | base64Decode -}}
    {{- end -}}