replicaCount: 1

spring:
  profiles:
    active: "prod"

vault:
  role: link-shortener-config-server-prod-role
  secretPath: kv/data/prod/link-shortener-config-server/config

  secretTemplate: |
    {{- with secret "kv/data/prod/link-shortener-config-server/config" -}}
    {{- range $key, $value := .Data.data }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}